Add scoop installation method
bloznelis/typioca pull request #67
Opened 2022-07-01 13:18 UTC by sitiom

Add scoop installation method. Also categorized the package managers via OS (Windows, Linux, and macOS) for organization.

2022-07-01 16:50 UTC, bloznelis requested changes
First of all, thanks for adding typioca to Scoop.

I don't think that there is a need to categorize these by operating systems. For example you can use Homebrew on Linux too.

And order of methods should be AUR > Brew > Scoop > Go.

2022-07-02 01:26 UTC, sitiom commented
> I don't think that there is a need to categorize these by operating systems. For example you can use Homebrew on Linux too.

Homebrew is definitely an exception, will separate that.

> And order of methods should be AUR > Brew > Scoop > Go.

There shouldn't be an "order" of methods to use; one can choose from the many available options.

2022-07-06 14:38 UTC, bloznelis commented
I'm pretty sure users are aware of their operating system and only care about specific package manager support.

> There shouldn't be an "order" of methods to use; one can choose from the many available options.

There should be an order, which is by relevancy. Windows users usually are not very terminal oriented bunch (and this is completely subjective opinion of mine). So as most of the users will be probably on Linux/Mac, these systems' package managers should be higher up the list, so they could be found faster.

2022-07-06 15:26 UTC, sitiom commented
> I'm pretty sure users are aware of their operating system and only care about specific package manager support.
> 
> > There shouldn't be an "order" of methods to use; one can choose from the many available options.
> 
> There should be an order, which is by relevancy. Windows users usually are not very terminal oriented bunch (and this is completely subjective opinion of mine). So as most of the users will be probably on Linux/Mac, these systems' package managers should be higher up the list, so they could be found faster.

This is what categorizing them is for, Linux/Mac users can find their package managers in their respective categories quickly. As support for more package managers appear, categorizing them can help organize the list and reduce clutter. Besides, they can also just use the search function.

2022-07-13 15:00 UTC, bloznelis commented
> Updates on this? I have sorted the list alphabetically (except for go), so the order is Homebrew > Linux > Windows > Go. What do you think?

Having "For Linux and macOS users" doesn't make much sense even if we add additional package manger support, as there are not many supported for both OS'es. I'd say dropping the OS names and sorting in alphabetical order is good enough then.

2022-07-13 15:18 UTC, sitiom commented
Done.

2022-07-14 06:32 UTC, bloznelis commented
It's not sorted in alphabetical order now ?

2022-07-14 06:52 UTC, sitiom commented
Ah right, fixed.

2022-07-14 08:04 UTC, bloznelis commented on README.md
> -**Note:** This will install typioca in `$GOBIN`, which defaults to `$GOPATH/bin` or `$HOME/go/bin` if the GOPATH environment variable is not set.
This note should not be removed

2022-07-14 08:56 UTC, merged

2022-07-14 08:57 UTC, bloznelis commented
Nice! Thank you for adding this to Scoop and your patience :clap: